name: Ma premiere CI

on:
  push:
    branches:
      - main
      - "feature/**" # Déclenche pour feature/docker, feature/calculatrice, etc.
      - "fix/**" # Déclenche pour toutes les branches de correction
  pull_request:
    branches:
      - main

jobs:
  verification:
    runs-on: ubuntu-latest
    steps:
      #      - name: Dire bonjour
      #        run: echo "Le pipeline vient de se declencher !"
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Configuration de .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Vérification du formatage (Linting)
        run: dotnet format --verify-no-changes --verbosity normal

      - name: Restaurer les dépendances
        run: dotnet restore MonProjet.sln

      - name: Compilation (Build)
        run: dotnet build MonProjet.sln --no-restore

      - name: Exécution des Tests
        run: dotnet test MonProjet.sln --no-restore --verbosity normal

      - name: Construction de l'image Docker
        run: docker build -t calculatrice-app-ci .
